import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import localFont from "next/font/local";

const raleway = localFont({
  src: "./fonts/Raleway.woff2",
  variable: "--font-raleway",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <ClerkProvider>
          <main className="overflow-hidden">{children}</main>
        </ClerkProvider>
      </body>
    </html>
  );
}
